### PR TITLE
Modulesync

### PR DESCRIPTION
**Pull request by smortex**
On hold until we have a new voxpupuli-test with:

* https://github.com/voxpupuli/voxpupuli-test/pull/40

This PR also include:

* #40 
* #41 
* #42

### CODE REVIEW

**Comment by smortex** [comment]
Just removed the `DELETE ME` commit, updated the modulesync commit and fixed the new issues.

This is now ready for review :tada:

**Review by root-expert — APPROVED** [review]
LGTM, are we gonna add support for OSes on different PR or you forgot it? :smile:

**Review by bastelfreak — APPROVED** [review]

**Comment by smortex** [comment]
> LGTM, are we gonna add support for OSes on different PR or you forgot it? smile

Yes, the first thing I would like to have is a working CI because it helps a lot!

@bastelfreak I think we usualy do merge commits but it seems to be disabled ATM. Do you want to enable it?

**Comment by bastelfreak** [comment]
ups, fixed it.

**Pull request merged**
